// TypeScript port of `crates/aegis-math` (`docs/phases/phase-09-sdk-ui.md` item 8).
//
// **Rust remains authoritative.** This module is NOT an independent source of truth -- every
// function here is validated bit-for-bit against `tests/vectors/*.json`, generated by the real
// Rust implementation (`test/vectors.test.ts`, `I-SDK-01`). If this file and `aegis-math` ever
// disagree, this file is wrong.
//
// Every quantity is `bigint`. JavaScript `number` is never used for a protocol-critical amount,
// rate, price, or share count -- `bigint` is exact and unbounded, so unlike Rust's `u128` this
// module does not need a 256-bit intermediate trick to avoid overflow during a multiply, but it
// still enforces the same u64/u128 *result* range checks Rust's `checked_*`/`try_from` calls do,
// so error behavior (not just success-path numbers) matches exactly.

export const WAD = 1_000_000_000_000_000_000n;
export const VIRTUAL_SHARES = 1_000_000n;
export const VIRTUAL_ASSETS = 1n;
export const SECONDS_PER_YEAR = 31_536_000n;

const U64_MAX = (1n << 64n) - 1n;
const U128_MAX = (1n << 128n) - 1n;

export type MathErrorCode = 'DivisionByZero' | 'Overflow';

export class MathError extends Error {
  readonly code: MathErrorCode;
  constructor(code: MathErrorCode) {
    super(`aegis-math: ${code}`);
    this.code = code;
    this.name = 'MathError';
  }
}

function checkU128(x: bigint): bigint {
  if (x < 0n || x > U128_MAX) throw new MathError('Overflow');
  return x;
}

function checkU64(x: bigint): bigint {
  if (x < 0n || x > U64_MAX) throw new MathError('Overflow');
  return x;
}

/** `floor(a*b/d)` (`crates/aegis-math/src/fixed.rs::mul_div_floor`). */
export function mulDivFloor(a: bigint, b: bigint, d: bigint): bigint {
  if (d === 0n) throw new MathError('DivisionByZero');
  return checkU128(a * b / d);
}

/** `ceil(a*b/d)` (`crates/aegis-math/src/fixed.rs::mul_div_ceil`). */
export function mulDivCeil(a: bigint, b: bigint, d: bigint): bigint {
  if (d === 0n) throw new MathError('DivisionByZero');
  return checkU128((a * b + d - 1n) / d);
}

// --- shares.rs ---

export function toSharesDown(assets: bigint, totalAssets: bigint, totalShares: bigint): bigint {
  const totalSharesOffset = checkU128(totalShares + VIRTUAL_SHARES);
  const totalAssetsOffset = checkU128(totalAssets + VIRTUAL_ASSETS);
  return mulDivFloor(assets, totalSharesOffset, totalAssetsOffset);
}

export function toSharesUp(assets: bigint, totalAssets: bigint, totalShares: bigint): bigint {
  const totalSharesOffset = checkU128(totalShares + VIRTUAL_SHARES);
  const totalAssetsOffset = checkU128(totalAssets + VIRTUAL_ASSETS);
  return mulDivCeil(assets, totalSharesOffset, totalAssetsOffset);
}

export function toAssetsDown(shares: bigint, totalAssets: bigint, totalShares: bigint): bigint {
  const totalAssetsOffset = checkU128(totalAssets + VIRTUAL_ASSETS);
  const totalSharesOffset = checkU128(totalShares + VIRTUAL_SHARES);
  return checkU64(mulDivFloor(shares, totalAssetsOffset, totalSharesOffset));
}

export function toAssetsUp(shares: bigint, totalAssets: bigint, totalShares: bigint): bigint {
  const totalAssetsOffset = checkU128(totalAssets + VIRTUAL_ASSETS);
  const totalSharesOffset = checkU128(totalShares + VIRTUAL_SHARES);
  return checkU64(mulDivCeil(shares, totalAssetsOffset, totalSharesOffset));
}

// --- irm.rs ---

export function utilization(totalBorrowAssets: bigint, totalSupplyAssets: bigint): bigint {
  if (totalSupplyAssets === 0n) return 0n;
  const u = mulDivFloor(totalBorrowAssets, WAD, totalSupplyAssets);
  return u < WAD ? u : WAD;
}

export function borrowRate(
  u: bigint,
  baseRatePs: bigint,
  slope1Ps: bigint,
  slope2Ps: bigint,
  uKink: bigint,
  maxRatePs: bigint,
): bigint {
  let r: bigint;
  if (u <= uKink) {
    r = baseRatePs + mulDivFloor(slope1Ps, u, uKink);
  } else {
    const aboveKink = u - uKink;
    const wadMinusKink = WAD - uKink;
    r = baseRatePs + slope1Ps + mulDivFloor(slope2Ps, aboveKink, wadMinusKink);
  }
  return r < maxRatePs ? r : maxRatePs;
}

/** Third-order Taylor expansion of `e^x - 1` (`crates/aegis-math/src/irm.rs::taylor3`). */
export function taylor3(x: bigint): bigint {
  const term2 = mulDivFloor(x, x, 2n * WAD);
  const xSquaredOverWad = mulDivFloor(x, x, WAD);
  const term3 = mulDivFloor(xSquaredOverWad, x, 6n * WAD);
  return checkU128(x + term2 + term3);
}

export function taylorX(ratePerSecondWad: bigint, dtSeconds: bigint): bigint {
  return checkU128(ratePerSecondWad * dtSeconds);
}

// --- health.rs ---

export const MIN_PRICE_WAD = 1_000_000n;
export const MAX_PRICE_WAD = 1_000_000_000_000_000_000_000_000_000_000n;

export type HealthErrorCode =
  | 'Overflow'
  | 'DivisionByZero'
  | 'PriceNotPositive'
  | 'ConfidenceTooWide'
  | 'PriceOutOfBounds';

export class HealthError extends Error {
  readonly code: HealthErrorCode;
  constructor(code: HealthErrorCode) {
    super(`aegis-math (health): ${code}`);
    this.code = code;
    this.name = 'HealthError';
  }
}

function asHealthError(err: unknown): never {
  if (err instanceof MathError) throw new HealthError(err.code);
  throw err;
}

function pow10(exp: number): bigint {
  if (exp < 0) throw new HealthError('Overflow');
  return 10n ** BigInt(exp);
}

/** `scale_to_wad_floor` (`crates/aegis-math/src/health.rs`). */
export function scaleToWadFloor(raw: bigint, expo: number): bigint {
  const shift = 18 + expo;
  if (shift >= 0) {
    return raw * pow10(shift);
  }
  const divisor = pow10(-shift);
  if (divisor === 0n) throw new HealthError('DivisionByZero');
  return raw / divisor;
}

/** `scale_to_wad_ceil`. */
export function scaleToWadCeil(raw: bigint, expo: number): bigint {
  const shift = 18 + expo;
  if (shift >= 0) {
    return raw * pow10(shift);
  }
  const divisor = pow10(-shift);
  if (divisor === 0n) throw new HealthError('DivisionByZero');
  return (raw + divisor - 1n) / divisor;
}

export interface PriceBandWad {
  lo: bigint;
  hi: bigint;
}

/** `conservative_price_band` (O-7/O-8/O-9, `crates/aegis-math/src/health.rs`). */
export function conservativePriceBand(
  price: bigint,
  conf: bigint,
  expo: number,
  maxConfBps: number,
): PriceBandWad {
  if (price <= 0n) throw new HealthError('PriceNotPositive');

  let maxConf: bigint;
  try {
    maxConf = mulDivFloor(price, BigInt(maxConfBps), 10_000n);
  } catch (err) {
    return asHealthError(err);
  }
  if (conf > maxConf) throw new HealthError('ConfidenceTooWide');

  const rawLo = price - conf > 1n ? price - conf : 1n;
  const rawHi = price + conf;

  const lo = scaleToWadFloor(rawLo, expo);
  const hi = scaleToWadCeil(rawHi, expo);

  if (lo < MIN_PRICE_WAD || hi > MAX_PRICE_WAD) throw new HealthError('PriceOutOfBounds');
  return { lo, hi };
}

export function collateralValue(
  collateralAmount: bigint,
  priceLoWad: bigint,
  collateralDecimals: number,
): bigint {
  try {
    return mulDivFloor(collateralAmount, priceLoWad, pow10(collateralDecimals));
  } catch (err) {
    return asHealthError(err);
  }
}

export function debtValue(debtAssets: bigint, priceHiWad: bigint, loanDecimals: number): bigint {
  try {
    return mulDivCeil(debtAssets, priceHiWad, pow10(loanDecimals));
  } catch (err) {
    return asHealthError(err);
  }
}

/** `HF = floor(collateral_value * liq_threshold / debt_value)`, or `u128::MAX` when there is no
 *  debt (`crates/aegis-math/src/health.rs::health_factor`). */
export function healthFactor(
  collateralValueWad: bigint,
  liqThreshold: bigint,
  debtValueWad: bigint,
): bigint {
  if (debtValueWad === 0n) return U128_MAX;
  try {
    return mulDivFloor(collateralValueWad, liqThreshold, debtValueWad);
  } catch (err) {
    return asHealthError(err);
  }
}

export function isWithinMaxLtv(
  collateralValueWad: bigint,
  debtValueWad: bigint,
  maxLtv: bigint,
): boolean {
  const maxDebtValue = mulDivFloor(collateralValueWad, maxLtv, WAD);
  return debtValueWad <= maxDebtValue;
}

/** SDK-only read model, never on-chain (`economic-model.md` §6.4): the collateral price at which
 *  this position becomes exactly liquidatable (`HF == WAD`). Returns `null` when there is no debt
 *  (a position with zero debt has no liquidation price). */
export function liquidationPrice(
  debtValueWad: bigint,
  collateralAmount: bigint,
  collateralDecimals: number,
  liqThreshold: bigint,
): bigint | null {
  if (debtValueWad === 0n || collateralAmount === 0n) return null;
  // price_c_liquidation = debt_value * 10^collateral_decimals / (collateral_amount * liq_threshold)
  const numerator = debtValueWad * pow10(collateralDecimals);
  const denominator = collateralAmount * liqThreshold;
  if (denominator === 0n) return null;
  return numerator / denominator;
}

// --- liquidation.rs ---

export type LiquidationErrorCode =
  | 'Overflow'
  | 'DivisionByZero'
  | 'ZeroRepay'
  | 'RepayExceedsMaxRepay'
  | 'SeizeExceedsCollateral';

export class LiquidationError extends Error {
  readonly code: LiquidationErrorCode;
  constructor(code: LiquidationErrorCode) {
    super(`aegis-math (liquidation): ${code}`);
    this.code = code;
    this.name = 'LiquidationError';
  }
}

function asLiquidationError(err: unknown): never {
  if (err instanceof MathError) throw new LiquidationError(err.code);
  throw err;
}

export interface LiquidationParams {
  collateralDecimals: number;
  loanDecimals: number;
  priceCLo: bigint;
  priceLHi: bigint;
  liqBonus: bigint;
  liqProtocolFee: bigint;
  closeFactor: bigint;
  fullLiqHf: bigint;
  minDebt: bigint;
}

export interface LiquidationOutcome {
  repayAssets: bigint;
  totalSeize: bigint;
  baseSeize: bigint;
  bonusAmount: bigint;
  protocolCut: bigint;
  toLiquidator: bigint;
  clamped: boolean;
}

/** `HF == WAD` is strictly NOT liquidatable (E-12, INV-LIQ-01). Never relax this to `<=`. */
export function isLiquidatable(hf: bigint): boolean {
  return hf < WAD;
}

export function maxRepay(debtAssets: bigint, hf: bigint, params: LiquidationParams): bigint {
  let repay: bigint;
  if (hf < params.fullLiqHf) {
    repay = debtAssets;
  } else {
    try {
      repay = mulDivFloor(debtAssets, params.closeFactor, WAD);
    } catch (err) {
      return asLiquidationError(err);
    }
  }
  const remaining = debtAssets - repay;
  if (remaining > 0n && remaining < params.minDebt) repay = debtAssets;
  return repay;
}

function repayToSeize(
  repayAssets: bigint,
  params: LiquidationParams,
): { repayValue: bigint; baseSeize: bigint; totalSeize: bigint; bonusAmount: bigint } {
  const loanScale = 10n ** BigInt(params.loanDecimals);
  const collateralScale = 10n ** BigInt(params.collateralDecimals);

  const repayValue = mulDivCeil(repayAssets, params.priceLHi, loanScale);
  const baseSeize = checkU64(mulDivFloor(repayValue, collateralScale, params.priceCLo));

  const bonusFactor = WAD + params.liqBonus;
  const bonusRepayValue = mulDivFloor(repayValue, bonusFactor, WAD);
  const totalSeize = checkU64(mulDivFloor(bonusRepayValue, collateralScale, params.priceCLo));

  const bonusAmount = totalSeize > baseSeize ? totalSeize - baseSeize : 0n;
  return { repayValue, baseSeize, totalSeize, bonusAmount };
}

function seizeToRepay(seizeCollateral: bigint, params: LiquidationParams): bigint {
  const collateralScale = 10n ** BigInt(params.collateralDecimals);
  const loanScale = 10n ** BigInt(params.loanDecimals);

  const seizeValue = mulDivCeil(seizeCollateral, params.priceCLo, collateralScale);
  const bonusFactor = WAD + params.liqBonus;
  const repayValue = mulDivCeil(seizeValue, WAD, bonusFactor);
  return checkU64(mulDivCeil(repayValue, loanScale, params.priceLHi));
}

function baseSeizeForRepay(repayAssets: bigint, params: LiquidationParams): bigint {
  const loanScale = 10n ** BigInt(params.loanDecimals);
  const collateralScale = 10n ** BigInt(params.collateralDecimals);
  const repayValue = mulDivCeil(repayAssets, params.priceLHi, loanScale);
  return checkU64(mulDivFloor(repayValue, collateralScale, params.priceCLo));
}

function protocolCutAndPayout(
  totalSeize: bigint,
  bonusAmount: bigint,
  liqProtocolFee: bigint,
): { protocolCut: bigint; toLiquidator: bigint } {
  const protocolCut = checkU64(mulDivFloor(bonusAmount, liqProtocolFee, WAD));
  const toLiquidator = totalSeize - protocolCut;
  if (toLiquidator < 0n) throw new LiquidationError('Overflow');
  return { protocolCut, toLiquidator };
}

/** `compute_liquidation_by_repay` (`economic-model.md` §7.1-7.3, `crates/aegis-math/src/
 *  liquidation.rs`). Preconditions the caller must separately enforce: `is_liquidatable(hf)` and
 *  oracle validity -- this function does not check either. */
export function computeLiquidationByRepay(
  params: LiquidationParams,
  debtAssets: bigint,
  collateralAmount: bigint,
  hf: bigint,
  repayAssets: bigint,
): LiquidationOutcome {
  if (repayAssets === 0n) throw new LiquidationError('ZeroRepay');
  const mr = maxRepay(debtAssets, hf, params);
  if (repayAssets > mr) throw new LiquidationError('RepayExceedsMaxRepay');

  let { baseSeize, totalSeize, bonusAmount } = repayToSeize(repayAssets, params);
  let clamped = false;
  let finalRepay = repayAssets;

  if (totalSeize > collateralAmount) {
    const clampedTotalSeize = collateralAmount;
    let newRepay = seizeToRepay(clampedTotalSeize, params);
    newRepay = newRepay < debtAssets ? newRepay : debtAssets;
    const newBase = baseSeizeForRepay(newRepay, params);
    const newBonus = clampedTotalSeize > newBase ? clampedTotalSeize - newBase : 0n;
    finalRepay = newRepay;
    totalSeize = clampedTotalSeize;
    baseSeize = newBase;
    bonusAmount = newBonus;
    clamped = true;
  }

  if (finalRepay === 0n) throw new LiquidationError('ZeroRepay');

  const { protocolCut, toLiquidator } = protocolCutAndPayout(
    totalSeize,
    bonusAmount,
    params.liqProtocolFee,
  );

  return {
    repayAssets: finalRepay,
    totalSeize,
    baseSeize,
    bonusAmount,
    protocolCut,
    toLiquidator,
    clamped,
  };
}

/** `compute_liquidation_by_seize`: liquidator names a target `seizeCollateral` instead of
 *  `repayAssets`. Takes no clamp path of its own -- a value exceeding `collateralAmount` is
 *  rejected, not silently reduced. */
export function computeLiquidationBySeize(
  params: LiquidationParams,
  debtAssets: bigint,
  collateralAmount: bigint,
  hf: bigint,
  seizeCollateral: bigint,
): LiquidationOutcome {
  if (seizeCollateral === 0n) throw new LiquidationError('ZeroRepay');
  if (seizeCollateral > collateralAmount) throw new LiquidationError('SeizeExceedsCollateral');

  let repayAssets = seizeToRepay(seizeCollateral, params);
  repayAssets = repayAssets < debtAssets ? repayAssets : debtAssets;
  if (repayAssets === 0n) throw new LiquidationError('ZeroRepay');

  const mr = maxRepay(debtAssets, hf, params);
  if (repayAssets > mr) throw new LiquidationError('RepayExceedsMaxRepay');

  const baseSeize = baseSeizeForRepay(repayAssets, params);
  const bonusAmount = seizeCollateral > baseSeize ? seizeCollateral - baseSeize : 0n;
  const { protocolCut, toLiquidator } = protocolCutAndPayout(
    seizeCollateral,
    bonusAmount,
    params.liqProtocolFee,
  );

  return {
    repayAssets,
    totalSeize: seizeCollateral,
    baseSeize,
    bonusAmount,
    protocolCut,
    toLiquidator,
    clamped: false,
  };
}
