skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
aegis = "2GtoBADM175vkjf5UYpbD198Ry1cJadXMGo8sCQvXndh"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"

[hooks]
