skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
aegis = "5emasbxEz9UGdeur6awt71JPE8ptvr716MUoVagaAPa1"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"

[hooks]
