//! The stateful fuzzer's action set, generator and executor
//! (`docs/testing-strategy.md` §5, `docs/phases/phase-10-security.md` #7-13).

use aegis_test_kit::{
    absorb_bad_debt, borrow, close_position, deposit_collateral, invariants, liquidate, repay,
    spl_token_2022_interface, spl_token_interface, supply,
    token_accounts::fetch_token_account_base, withdraw, withdraw_collateral,
    withdraw_collateral_fees, PriceFixture,
};
use rand::Rng;
use solana_pubkey::Pubkey;
use solana_signer::Signer;

use crate::ledger::Ledger;
use crate::sampling::{biased_amount, biased_price_move_bps, biased_time_delta};
use crate::world::{World, ATTACKER, BORROWER_A, BORROWER_B, LIQUIDATOR};

#[derive(Clone, Debug)]
pub enum Action {
    DepositCollateral {
        amount: u64,
    },
    WithdrawCollateral {
        amount: u64,
    },
    Supply {
        assets: u64,
    },
    Withdraw {
        assets: u64,
    },
    Borrow {
        assets: u64,
    },
    Repay {
        assets: u64,
    },
    AccrueInterest,
    Liquidate {
        repay_assets: u64,
        seize_collateral: u64,
    },
    AbsorbBadDebt,
    ClosePosition,
    WarpTime {
        delta_secs: i64,
    },
    MovePrice {
        collateral: bool,
        bps: i64,
    },
    DirectDonation {
        amount: u64,
        collateral: bool,
    },
    WithdrawCollateralFees {
        amount: u64,
    },
}

#[derive(Clone, Debug)]
pub struct Step {
    pub market_idx: usize,
    /// Who signs/pays for the action.
    pub actor_idx: usize,
    /// Whose position is affected (differs from `actor_idx` for `Liquidate`/`AbsorbBadDebt`).
    pub target_idx: usize,
    pub action: Action,
}

#[derive(Debug, Default, Clone, Copy)]
pub struct StepStats {
    pub succeeded: bool,
}

/// Generates one step, biasing both the action kind and its amount toward states that are
/// actually interesting for a lending protocol (`testing-strategy.md` §5's weighted-choice loop).
pub fn generate_step<R: Rng + ?Sized>(rng: &mut R, world: &World) -> Step {
    let market_idx = rng.gen_range(0..world.markets.len());
    let m = &world.markets[market_idx];

    // Weighted action-kind choice. Weights are deliberately not uniform: state-changing lending
    // actions dominate, with warp_time/move_price frequent enough to matter (phase-10-security.md
    // #9/#10: "first-class operations"), and admin/absorb rarer, matching how often they'd occur
    // in a real operational sequence.
    //
    // Deliberately EXCLUDED from this generator (`Action::ClosePosition`/`Action::DirectDonation`
    // remain implemented and callable, just never generated by the main loop):
    // - `close_position` requires all three balances exactly zero, which a freshly-initialized,
    //   not-yet-used actor position trivially satisfies -- closing it here would defund a PDA this
    //   world's fixed per-(market, actor) position list assumes exists for the rest of the run,
    //   and every subsequent `assert_all_global` call would then panic trying to fetch a position
    //   that no longer exists. `close_position` is already covered on its own terms by
    //   `U-LIFE-01`/`A-LIFE-02`; re-deriving that coverage here would need this world to support
    //   re-`init_position`-ing mid-run, which is unnecessary complexity for an action outside
    //   `phase-10-security.md` #8's required action list.
    // - `direct_donation` is INV-CUS-08's attack: by design (see `docs/invariants.md` §B) a
    //   donation is NEVER credited to any position or market total, which means it PERMANENTLY
    //   breaks INV-CUS-01/02's exact-equality form for the rest of the run the moment it succeeds
    //   -- not a bug the fuzzer should "catch" mid-stream, but a standing, documented exception
    //   this checker's exact-equality design cannot coexist with once triggered. `A-CUS-08` and
    //   `assert_inv_cus_02_detects_uncredited_donation` already prove this exact behavior in
    //   isolation; mixing it into the [GLOBAL]-invariant-checked main loop would make every later
    //   step a false positive, not a real finding.
    let choices: &[(u32, &str)] = &[
        (13, "deposit_collateral"),
        (11, "withdraw_collateral"),
        (13, "supply"),
        (11, "withdraw"),
        (13, "borrow"),
        (13, "repay"),
        (9, "accrue_interest"),
        (11, "liquidate"),
        (5, "absorb_bad_debt"),
        (11, "warp_time"),
        (11, "move_price"),
        (2, "withdraw_collateral_fees"),
    ];
    let total: u32 = choices.iter().map(|(w, _)| w).sum();
    let mut pick = rng.gen_range(0..total);
    let mut kind = choices[0].1;
    for (w, name) in choices {
        if pick < *w {
            kind = name;
            break;
        }
        pick -= w;
    }

    let random_actor = rng.gen_range(0..world.actors.len());
    let random_borrower = if rng.gen_bool(0.5) {
        BORROWER_A
    } else {
        BORROWER_B
    };

    match kind {
        "deposit_collateral" => {
            let bal = m
                .collateral_atas
                .get(random_actor)
                .map(|_| 0u64)
                .unwrap_or(0);
            let _ = bal;
            let amount = biased_amount(rng, 1_000_000_000, None);
            Step {
                market_idx,
                actor_idx: random_actor,
                target_idx: random_actor,
                action: Action::DepositCollateral { amount },
            }
        }
        "withdraw_collateral" => {
            let amount = biased_amount(rng, 1_000_000_000, None);
            Step {
                market_idx,
                actor_idx: random_actor,
                target_idx: random_actor,
                action: Action::WithdrawCollateral { amount },
            }
        }
        "supply" => {
            let amount = biased_amount(rng, 100_000_000_000, None);
            Step {
                market_idx,
                actor_idx: random_actor,
                target_idx: random_actor,
                action: Action::Supply { assets: amount },
            }
        }
        "withdraw" => {
            let amount = biased_amount(rng, 100_000_000_000, None);
            Step {
                market_idx,
                actor_idx: random_actor,
                target_idx: random_actor,
                action: Action::Withdraw { assets: amount },
            }
        }
        "borrow" => {
            let amount = biased_amount(rng, 100_000_000, Some(10_000_000));
            Step {
                market_idx,
                actor_idx: random_borrower,
                target_idx: random_borrower,
                action: Action::Borrow { assets: amount },
            }
        }
        "repay" => {
            let amount = biased_amount(rng, 100_000_000, Some(10_000_000));
            Step {
                market_idx,
                actor_idx: random_borrower,
                target_idx: random_borrower,
                action: Action::Repay { assets: amount },
            }
        }
        "accrue_interest" => Step {
            market_idx,
            actor_idx: random_actor,
            target_idx: random_actor,
            action: Action::AccrueInterest,
        },
        "liquidate" => {
            // Biased toward the TARGET's own live state (phase-10-security.md #11: "collateral
            // amount, collateral ±1", "debt amount, debt ±1") rather than a generic fixed bound --
            // this is what makes a FULL liquidation (collateral_amount -> exactly 0, the
            // precondition `absorb_bad_debt` needs) a common outcome instead of a rare accident,
            // so bad-debt states are actually reachable within the fuzz budget.
            let target_position = world.fetch_position_state(market_idx, random_borrower);
            let target_market = world.fetch_market_state(market_idx);
            let target_debt_assets = target_position
                .borrow_shares
                .saturating_mul(target_market.total_borrow_assets as u128)
                .checked_div(target_market.total_borrow_shares)
                .unwrap_or(0) as u64;
            let repay_assets = biased_amount(rng, target_debt_assets.max(1), None);
            let seize_collateral = biased_amount(rng, target_position.collateral_amount, None);
            Step {
                market_idx,
                actor_idx: LIQUIDATOR,
                target_idx: random_borrower,
                action: Action::Liquidate {
                    repay_assets,
                    seize_collateral,
                },
            }
        }
        "absorb_bad_debt" => Step {
            market_idx,
            actor_idx: LIQUIDATOR,
            target_idx: random_borrower,
            action: Action::AbsorbBadDebt,
        },
        "close_position" => Step {
            market_idx,
            actor_idx: random_actor,
            target_idx: random_actor,
            action: Action::ClosePosition,
        },
        "warp_time" => Step {
            market_idx,
            actor_idx: random_actor,
            target_idx: random_actor,
            action: Action::WarpTime {
                delta_secs: biased_time_delta(rng),
            },
        },
        "move_price" => Step {
            market_idx,
            actor_idx: random_actor,
            target_idx: random_actor,
            action: Action::MovePrice {
                collateral: rng.gen_bool(0.5),
                bps: biased_price_move_bps(rng),
            },
        },
        "direct_donation" => Step {
            market_idx,
            actor_idx: ATTACKER,
            target_idx: ATTACKER,
            action: Action::DirectDonation {
                amount: biased_amount(rng, 1_000_000_000, None),
                collateral: rng.gen_bool(0.5),
            },
        },
        "withdraw_collateral_fees" => Step {
            market_idx,
            actor_idx: random_actor,
            target_idx: random_actor,
            action: Action::WithdrawCollateralFees {
                amount: biased_amount(rng, 1_000_000, None),
            },
        },
        _ => unreachable!(),
    }
}

fn apply_price(
    m: &crate::world::MarketCtx,
    collateral: bool,
    bps: i64,
    now: i64,
) -> (i64, u64, i32) {
    let (price, conf, expo) = if collateral {
        m.collateral_price
    } else {
        m.loan_price
    };
    let delta = (price as i128 * bps as i128 / 10_000) as i64;
    let new_price = (price + delta).max(1);
    let _ = now;
    (new_price, conf, expo)
}

/// Executes one step against `world`, updates the value-creation ledger on success, and asserts
/// every applicable **[GLOBAL]** invariant afterward -- whether the step succeeded or failed
/// (`testing-strategy.md` §5). On failure, also asserts the atomicity property (#12/#49): the
/// market, target position, both vaults and the acting actor's own wallet ATAs are byte-identical
/// to their pre-step snapshot.
pub fn execute_step(world: &mut World, step: &Step) -> StepStats {
    let admin = world.admin.insecure_clone();
    let market_idx = step.market_idx;
    let actor_idx = step.actor_idx;
    let target_idx = step.target_idx;

    world.markets[market_idx].ledger.ensure(world.actors.len());

    // --- snapshot for the failure-atomicity check ---
    let m = &world.markets[market_idx];
    let market_pk = m.market;
    let target_position_pk = m.positions[target_idx];
    let collateral_vault_pk = m.collateral_vault;
    let loan_vault_pk = m.loan_vault;
    let actor_collateral_ata = m.collateral_atas[actor_idx];
    let actor_loan_ata = m.loan_atas[actor_idx];

    let snap = |svm: &litesvm::LiteSVM, pk: Pubkey| -> Vec<u8> {
        svm.get_account(&pk).map(|a| a.data).unwrap_or_default()
    };
    let before_market_bytes = snap(&world.svm, market_pk);
    let before_position_bytes = snap(&world.svm, target_position_pk);
    let before_cvault_bytes = snap(&world.svm, collateral_vault_pk);
    let before_lvault_bytes = snap(&world.svm, loan_vault_pk);
    let before_actor_cata_bytes = snap(&world.svm, actor_collateral_ata);
    let before_actor_lata_bytes = snap(&world.svm, actor_loan_ata);

    let before_actor_loan_bal = fetch_token_account_base(&world.svm, &actor_loan_ata).amount;
    let before_actor_collateral_bal =
        fetch_token_account_base(&world.svm, &actor_collateral_ata).amount;

    let market_before_for_accrual = if matches!(step.action, Action::AccrueInterest) {
        Some(world.fetch_market_state(market_idx))
    } else {
        None
    };

    // `WarpTime`/`MovePrice` are direct sysvar/fixture mutations, not submitted transactions --
    // they always "succeed" and are handled before the `TransactionResult`-based dispatch below.
    if let Action::WarpTime { delta_secs } = &step.action {
        let mut clock = world.svm.get_sysvar::<solana_clock::Clock>();
        clock.unix_timestamp = clock.unix_timestamp.saturating_add(*delta_secs);
        world.svm.set_sysvar(&clock);

        let positions = world.all_positions(market_idx);
        let m = &world.markets[market_idx];
        invariants::assert_all_global(&world.svm, &m.market, &positions, &m.fee_position);
        return StepStats { succeeded: true };
    }
    if let Action::MovePrice { collateral, bps } = &step.action {
        let now = world.now();
        let (new_price, conf, expo) = {
            let m = &world.markets[market_idx];
            apply_price(m, *collateral, *bps, now)
        };
        let (feed_id, pubkey) = {
            let m = &world.markets[market_idx];
            if *collateral {
                (m.collateral_feed_id, m.collateral_price_pubkey)
            } else {
                (m.loan_feed_id, m.loan_price_pubkey)
            }
        };
        aegis_test_kit::inject_price_update(
            &mut world.svm,
            pubkey,
            PriceFixture::valid(feed_id, new_price, conf, expo, now),
        );
        let m = &mut world.markets[market_idx];
        if *collateral {
            m.collateral_price = (new_price, conf, expo);
        } else {
            m.loan_price = (new_price, conf, expo);
        }

        let positions = world.all_positions(market_idx);
        let m = &world.markets[market_idx];
        invariants::assert_all_global(&world.svm, &m.market, &positions, &m.fee_position);
        return StepStats { succeeded: true };
    }

    let result: litesvm::types::TransactionResult = {
        let actor_kp = world.actors[actor_idx].insecure_clone();
        let m = &world.markets[market_idx];
        match &step.action {
            Action::DepositCollateral { amount } => deposit_collateral(
                &mut world.svm,
                &actor_kp,
                m.market,
                m.positions[actor_idx],
                m.collateral_vault,
                m.collateral_atas[actor_idx],
                m.collateral_mint,
                m.collateral_token_program,
                *amount,
            ),
            Action::WithdrawCollateral { amount } => withdraw_collateral(
                &mut world.svm,
                &actor_kp,
                m.market,
                m.positions[actor_idx],
                m.collateral_vault,
                m.collateral_atas[actor_idx],
                m.collateral_mint,
                m.collateral_token_program,
                m.collateral_price_pubkey,
                m.loan_price_pubkey,
                *amount,
            ),
            Action::Supply { assets } => supply(
                &mut world.svm,
                &actor_kp,
                m.market,
                m.positions[actor_idx],
                m.fee_position,
                m.loan_vault,
                m.loan_atas[actor_idx],
                m.loan_mint,
                m.loan_token_program,
                *assets,
                0,
            ),
            Action::Withdraw { assets } => withdraw(
                &mut world.svm,
                &actor_kp,
                m.market,
                m.positions[actor_idx],
                m.fee_position,
                m.loan_vault,
                m.loan_atas[actor_idx],
                m.loan_mint,
                m.loan_token_program,
                *assets,
                0,
            ),
            Action::Borrow { assets } => borrow(
                &mut world.svm,
                &actor_kp,
                m.market,
                m.positions[actor_idx],
                m.fee_position,
                m.loan_vault,
                m.loan_atas[actor_idx],
                m.loan_mint,
                m.loan_token_program,
                m.collateral_price_pubkey,
                m.loan_price_pubkey,
                *assets,
                0,
            ),
            Action::Repay { assets } => repay(
                &mut world.svm,
                &actor_kp,
                m.market,
                m.positions[actor_idx],
                m.fee_position,
                m.loan_vault,
                m.loan_atas[actor_idx],
                m.loan_mint,
                m.loan_token_program,
                *assets,
                0,
            ),
            Action::AccrueInterest => {
                aegis_test_kit::accrue_interest(&mut world.svm, &actor_kp, m.market, m.fee_position)
            }
            Action::Liquidate {
                repay_assets,
                seize_collateral,
            } => liquidate(
                &mut world.svm,
                &actor_kp,
                m.market,
                m.positions[target_idx],
                m.fee_position,
                m.loan_vault,
                m.collateral_vault,
                m.loan_atas[actor_idx],
                m.collateral_atas[actor_idx],
                m.loan_mint,
                m.collateral_mint,
                m.loan_token_program,
                m.collateral_token_program,
                m.collateral_price_pubkey,
                m.loan_price_pubkey,
                *repay_assets,
                *seize_collateral,
            ),
            Action::AbsorbBadDebt => absorb_bad_debt(
                &mut world.svm,
                &actor_kp,
                m.market,
                m.positions[target_idx],
                m.fee_position,
            ),
            Action::ClosePosition => {
                close_position(&mut world.svm, &actor_kp, m.market, m.positions[actor_idx])
            }
            Action::WithdrawCollateralFees { amount } => withdraw_collateral_fees(
                &mut world.svm,
                &admin,
                m.market,
                m.collateral_vault,
                m.collateral_atas[actor_idx],
                m.collateral_mint,
                m.collateral_token_program,
                *amount,
            ),
            Action::WarpTime { .. } | Action::MovePrice { .. } => {
                unreachable!("handled by the early return above, before this dispatch")
            }
            Action::DirectDonation { amount, collateral } => {
                let (mint, vault, token_program, decimals, ata) = if *collateral {
                    (
                        m.collateral_mint,
                        m.collateral_vault,
                        m.collateral_token_program,
                        9u8,
                        m.collateral_atas[actor_idx],
                    )
                } else {
                    (
                        m.loan_mint,
                        m.loan_vault,
                        m.loan_token_program,
                        6u8,
                        m.loan_atas[actor_idx],
                    )
                };
                send_direct_donation(
                    &mut world.svm,
                    &actor_kp,
                    ata,
                    mint,
                    vault,
                    token_program,
                    decimals,
                    *amount,
                )
            }
        }
    };

    let succeeded = result.is_ok();

    if succeeded {
        record_ledger_effects(
            world,
            step,
            before_actor_loan_bal,
            before_actor_collateral_bal,
        );
        if let (Action::AccrueInterest, Some(before_state)) =
            (&step.action, &market_before_for_accrual)
        {
            let after_state = world.fetch_market_state(market_idx);
            invariants::assert_inv_acc_04(before_state, &after_state);
            let delta_supply = after_state
                .total_supply_assets
                .saturating_sub(before_state.total_supply_assets);
            world.markets[market_idx]
                .ledger
                .record_interest(delta_supply);
        }
        if matches!(
            step.action,
            Action::Borrow { .. } | Action::WithdrawCollateral { .. }
        ) {
            let m = &world.markets[market_idx];
            let (c_price, _, c_expo) = m.collateral_price;
            let (l_price, _, l_expo) = m.loan_price;
            // Recompute the same conservative band the program itself validated for this action
            // (INV-ORA-03: zero confidence in this fixture, so lo==hi==the scaled price).
            let c_lo = scale_to_wad(c_price, c_expo);
            let l_hi = scale_to_wad(l_price, l_expo);
            invariants::assert_inv_solv_01(
                &world.svm,
                &m.market,
                &m.positions[target_idx],
                c_lo,
                l_hi,
            );
        }
    } else {
        assert_eq!(
            snap(&world.svm, market_pk),
            before_market_bytes,
            "atomicity: market mutated on a failed step {step:?}"
        );
        assert_eq!(
            snap(&world.svm, target_position_pk),
            before_position_bytes,
            "atomicity: position mutated on a failed step {step:?}"
        );
        assert_eq!(
            snap(&world.svm, collateral_vault_pk),
            before_cvault_bytes,
            "atomicity: collateral_vault mutated on a failed step {step:?}"
        );
        assert_eq!(
            snap(&world.svm, loan_vault_pk),
            before_lvault_bytes,
            "atomicity: loan_vault mutated on a failed step {step:?}"
        );
        assert_eq!(
            snap(&world.svm, actor_collateral_ata),
            before_actor_cata_bytes,
            "atomicity: actor collateral ATA mutated on a failed step {step:?}"
        );
        assert_eq!(
            snap(&world.svm, actor_loan_ata),
            before_actor_lata_bytes,
            "atomicity: actor loan ATA mutated on a failed step {step:?}"
        );
    }

    // Every [GLOBAL] invariant checkable from a snapshot, after every step, success or failure.
    let positions = world.all_positions(market_idx);
    let m = &world.markets[market_idx];
    invariants::assert_all_global(&world.svm, &m.market, &positions, &m.fee_position);

    StepStats { succeeded }
}

fn scale_to_wad(price: i64, expo: i32) -> u128 {
    // Mirrors aegis_math::health's zero-confidence case exactly: lo == hi == price scaled to WAD.
    const WAD: i128 = 1_000_000_000_000_000_000;
    let price = price as i128;
    let scaled = if expo <= 0 {
        let divisor = 10i128.pow((-expo) as u32);
        price * WAD / divisor
    } else {
        price * WAD * 10i128.pow(expo as u32)
    };
    scaled as u128
}

fn record_ledger_effects(
    world: &mut World,
    step: &Step,
    before_actor_loan_bal: u64,
    before_actor_collateral_bal: u64,
) {
    let market_idx = step.market_idx;
    let actor_idx = step.actor_idx;
    let m = &world.markets[market_idx];
    let actor_loan_ata = m.loan_atas[actor_idx];
    let actor_collateral_ata = m.collateral_atas[actor_idx];
    let after_actor_loan_bal = fetch_token_account_base(&world.svm, &actor_loan_ata).amount;
    let after_actor_collateral_bal =
        fetch_token_account_base(&world.svm, &actor_collateral_ata).amount;

    let ledger: &mut Ledger = &mut world.markets[market_idx].ledger;
    match step.action {
        Action::Supply { .. } | Action::Repay { .. } => {
            let delta = before_actor_loan_bal.saturating_sub(after_actor_loan_bal);
            ledger.record_loan_in(actor_idx, delta);
        }
        Action::Withdraw { .. } | Action::Borrow { .. } => {
            let delta = after_actor_loan_bal.saturating_sub(before_actor_loan_bal);
            ledger.record_loan_out(actor_idx, delta);
        }
        Action::DepositCollateral { .. } => {
            let delta = before_actor_collateral_bal.saturating_sub(after_actor_collateral_bal);
            ledger.record_collateral_in(actor_idx, delta);
        }
        Action::WithdrawCollateral { .. } => {
            let delta = after_actor_collateral_bal.saturating_sub(before_actor_collateral_bal);
            ledger.record_collateral_out(actor_idx, delta);
        }
        Action::Liquidate { .. } => {
            let loan_delta = before_actor_loan_bal.saturating_sub(after_actor_loan_bal);
            ledger.record_loan_in(actor_idx, loan_delta);
            let collateral_delta =
                after_actor_collateral_bal.saturating_sub(before_actor_collateral_bal);
            ledger.record_liquidation_collateral_received(actor_idx, collateral_delta);
        }
        _ => {}
    }
}

#[allow(clippy::too_many_arguments, clippy::result_large_err)]
fn send_direct_donation(
    svm: &mut litesvm::LiteSVM,
    payer: &solana_keypair::Keypair,
    source: Pubkey,
    mint: Pubkey,
    destination: Pubkey,
    token_program: Pubkey,
    decimals: u8,
    amount: u64,
) -> litesvm::types::TransactionResult {
    let ix = if token_program == spl_token_2022_interface::ID {
        spl_token_2022_interface::instruction::transfer_checked(
            &token_program,
            &source,
            &mint,
            &destination,
            &payer.pubkey(),
            &[],
            amount,
            decimals,
        )
    } else {
        spl_token_interface::instruction::transfer_checked(
            &token_program,
            &source,
            &mint,
            &destination,
            &payer.pubkey(),
            &[],
            amount,
            decimals,
        )
    }
    .expect("valid transfer_checked instruction");

    let blockhash = svm.latest_blockhash();
    let message =
        solana_message::Message::new_with_blockhash(&[ix], Some(&payer.pubkey()), &blockhash);
    let tx = solana_transaction::versioned::VersionedTransaction::try_new(
        solana_message::VersionedMessage::Legacy(message),
        &[payer],
    )
    .expect("sign direct-donation transaction");
    svm.send_transaction(tx)
}
