//! Multi-market, multi-actor world for the Phase 10 stateful invariant fuzzer
//! (`docs/phases/phase-10-security.md`, `docs/testing-strategy.md` §5).
//!
//! Two markets exist in every run, exercised in the SAME LiteSVM instance so cross-market
//! isolation (INV-RES-03, `A-PAR-02`) is genuinely tested under interleaved random operations, not
//! merely asserted once at setup:
//! - **Market 0** — classic SPL/SPL, SOL(9dp)/USDC(6dp) reference parameters
//!   (`reference_market_args`), identical to every earlier phase's fixture.
//! - **Market 1** — Token-2022 transfer-fee collateral / classic SPL loan, so the fuzzer's custody
//!   invariants (INV-CUS-01/02) are meaningfully exercised on a fee-bearing path (T-14), not just
//!   the fee-free path every other market in this repository already covers.
//!
//! Six actors (`docs/phases/phase-10-security.md` #15): two lenders, two borrowers, one
//! liquidator, one "attacker". The attacker participates in every ordinary permissionless action
//! exactly like the other five (a deliberate test of the design's own claim that no role gets
//! special treatment) and is also the reserved actor for `Action::DirectDonation` -- implemented
//! and callable, but not generated by the main random loop; see `actions::generate_step`'s doc
//! comment for exactly why mixing an INV-CUS-08 donation into the [GLOBAL]-invariant-checked
//! stream would make every later step a false positive rather than a real finding.

#![allow(dead_code)]

use aegis_test_kit::{
    create_market, create_spl_mint, create_token_2022_mint, create_token_account, deploy,
    fetch_market, fetch_position, init_position, initialize_protocol, mint_to,
    reference_market_args, set_price, spl_token_2022_interface, spl_token_interface, PriceFixture,
    Token2022Extension,
};
use litesvm::LiteSVM;
use solana_keypair::Keypair;
use solana_pubkey::Pubkey;
use solana_signer::Signer;

use crate::ledger::Ledger;

pub const NUM_ACTORS: usize = 6;
pub const LENDER_A: usize = 0;
pub const LENDER_B: usize = 1;
pub const BORROWER_A: usize = 2;
pub const BORROWER_B: usize = 3;
pub const LIQUIDATOR: usize = 4;
pub const ATTACKER: usize = 5;
pub const ACTOR_NAMES: [&str; NUM_ACTORS] = [
    "lender_a",
    "lender_b",
    "borrower_a",
    "borrower_b",
    "liquidator",
    "attacker",
];

/// A deterministic, reproducible seed source: every keypair and mint in the world is derived from
/// a counter seeded by the campaign seed, never `Keypair::new()` (`docs/zero-cost-demo.md` §6,
/// `phase-10-security.md`: "all keypairs ... are seeded").
pub struct SeedGen {
    next: u16,
    base: u64,
}
impl SeedGen {
    pub fn new(base: u64) -> Self {
        Self { next: 1, base }
    }
    /// One deterministic byte per call — enough distinct values for one fuzz world's fixed setup
    /// (mints, vaults, actors); campaign-level per-step randomness comes from `StdRng`, not this.
    pub fn next_byte(&mut self) -> u8 {
        let v = self.next;
        self.next = self.next.checked_add(1).expect("seed space exhausted");
        // Mix in the campaign base seed so two different seeds never collide on the same fixed
        // keypair/mint bytes, while staying a deterministic pure function of (base, call index).
        ((self.base.wrapping_add(v as u64)) & 0xFF) as u8
    }
}

pub struct MarketCtx {
    pub label: &'static str,
    pub market: Pubkey,
    pub fee_position: Pubkey,
    pub collateral_vault: Pubkey,
    pub loan_vault: Pubkey,
    pub collateral_mint: Pubkey,
    pub loan_mint: Pubkey,
    pub collateral_token_program: Pubkey,
    pub loan_token_program: Pubkey,
    pub collateral_feed_id: [u8; 32],
    pub loan_feed_id: [u8; 32],
    /// Fixed price-update account addresses this market's oracle reads from -- `move_price`
    /// re-injects a fixture at the SAME address with a new price, exactly like a real Pyth
    /// publisher posting an update (never a new pubkey per price move).
    pub collateral_price_pubkey: Pubkey,
    pub loan_price_pubkey: Pubkey,
    /// Current raw (price, conf, expo) the fuzzer believes is injected -- mutated only by
    /// `move_price`, read by every action that needs to reason about health/LTV.
    pub collateral_price: (i64, u64, i32),
    pub loan_price: (i64, u64, i32),
    /// Per-actor Position PDA in this market (all actors get one up front via `init_position`).
    pub positions: Vec<Pubkey>,
    /// Per-actor collateral-mint and loan-mint ATAs in this market.
    pub collateral_atas: Vec<Pubkey>,
    pub loan_atas: Vec<Pubkey>,
    pub ledger: Ledger,
    pub is_token2022_fee_market: bool,
}

pub struct World {
    pub svm: LiteSVM,
    pub admin: Keypair,
    pub actors: Vec<Keypair>,
    pub markets: Vec<MarketCtx>,
}

const COLLATERAL_FEED_M0: [u8; 32] = [0xA0u8; 32];
const LOAN_FEED_M0: [u8; 32] = [0xB0u8; 32];
const COLLATERAL_FEED_M1: [u8; 32] = [0xA1u8; 32];
const LOAN_FEED_M1: [u8; 32] = [0xB1u8; 32];

const REFERENCE_COLLATERAL_PRICE: (i64, u64, i32) = (15_000_000_000, 0, -8); // $150.00
const REFERENCE_LOAN_PRICE: (i64, u64, i32) = (100_000_000, 0, -8); // $1.00

/// Actors start with a generous wallet balance so the biased sampler's "near-max"/"exact-balance"
/// cases are meaningful relative to real headroom, not immediately precondition-rejected.
const INITIAL_LOAN_BALANCE: u64 = 1_000_000_000_000; // 1,000,000 USDC @ 6dp
const INITIAL_COLLATERAL_BALANCE: u64 = 1_000_000_000_000; // 1,000 SOL @ 9dp

fn program_bytes() -> &'static [u8] {
    include_bytes!(concat!(env!("CARGO_TARGET_TMPDIR"), "/../deploy/aegis.so"))
}

fn fund_actor(svm: &mut LiteSVM, actor: &Keypair) {
    svm.airdrop(&actor.pubkey(), 50_000_000_000)
        .expect("airdrop actor");
}

/// Builds a fresh, deterministic world for campaign seed `seed`. Every mint, vault, actor keypair
/// and initial price is a pure function of `seed`, so a failing seed is fully reproducible
/// (`phase-10-security.md` "Determinism").
pub fn build_world(seed: u64) -> World {
    let (mut svm, deployer) = deploy(aegis::ID, program_bytes());
    let mut seeds = SeedGen::new(seed);

    let admin = Keypair::new_from_array([seeds.next_byte(); 32]);
    svm.airdrop(&admin.pubkey(), 100_000_000_000)
        .expect("airdrop admin");
    // The deterministic test-kit payer already has funds; reuse it to avoid a redundant airdrop.
    let _ = &deployer;

    let guardian = Keypair::new_from_array([seeds.next_byte(); 32]).pubkey();
    let fee_recipient = Keypair::new_from_array([seeds.next_byte(); 32]).pubkey();
    initialize_protocol(&mut svm, &admin, guardian, fee_recipient).expect("initialize_protocol");

    let mut actors = Vec::with_capacity(NUM_ACTORS);
    for _ in 0..NUM_ACTORS {
        let kp = Keypair::new_from_array([seeds.next_byte(); 32]);
        fund_actor(&mut svm, &kp);
        actors.push(kp);
    }

    // --- Market 0: classic SPL/SPL ---
    let m0_collateral_mint =
        create_spl_mint(&mut svm, &admin, seeds.next_byte(), 9, admin.pubkey(), None);
    let m0_loan_mint =
        create_spl_mint(&mut svm, &admin, seeds.next_byte(), 6, admin.pubkey(), None);
    let mut m0_args = reference_market_args(0, COLLATERAL_FEED_M0, LOAN_FEED_M0, false);
    // `reference_market_args`'s own defaults are a zero-rate IRM (base/slope1/slope2_ps == 0),
    // deliberately so for tests that want share/asset math without interest complicating it. This
    // fuzzer needs the OPPOSITE: real, nonzero interest accrual to ever occur so INV-ACC-04 (and
    // the `AccrueInterest` action generally) has anything to exercise. Real, non-placeholder
    // per-second WAD rates already used elsewhere in this repository
    // (`tests/phase4_lending.rs`/`phase6_integration.rs`: "4% APR at the kink" / "+100% APR above
    // the kink").
    m0_args.slope1_ps = 1_268_391_679;
    m0_args.slope2_ps = 31_709_791_983;
    let (res0, m0_market, m0_cvault, m0_lvault, m0_fee_position) = create_market(
        &mut svm,
        &admin,
        m0_collateral_mint,
        m0_loan_mint,
        spl_token_interface::ID,
        spl_token_interface::ID,
        fee_recipient,
        m0_args,
    );
    res0.expect("market 0 create_market");

    // --- Market 1: Token-2022 transfer-fee collateral / classic SPL loan ---
    let m1_collateral_mint = create_token_2022_mint(
        &mut svm,
        &admin,
        seeds.next_byte(),
        9,
        admin.pubkey(),
        None,
        &[Token2022Extension::TransferFeeConfig {
            basis_points: 50, // 0.5%
            maximum_fee: u64::MAX,
        }],
    );
    let m1_loan_mint =
        create_spl_mint(&mut svm, &admin, seeds.next_byte(), 6, admin.pubkey(), None);
    let mut m1_args = reference_market_args(1, COLLATERAL_FEED_M1, LOAN_FEED_M1, false);
    m1_args.slope1_ps = 1_268_391_679;
    m1_args.slope2_ps = 31_709_791_983;
    let (res1, m1_market, m1_cvault, m1_lvault, m1_fee_position) = create_market(
        &mut svm,
        &admin,
        m1_collateral_mint,
        m1_loan_mint,
        spl_token_2022_interface::ID,
        spl_token_interface::ID,
        fee_recipient,
        m1_args,
    );
    res1.expect("market 1 create_market");

    let now = svm.get_sysvar::<solana_clock::Clock>().unix_timestamp;
    let m0_c_price_pk = set_price(
        &mut svm,
        seeds.next_byte(),
        PriceFixture::valid(
            COLLATERAL_FEED_M0,
            REFERENCE_COLLATERAL_PRICE.0,
            REFERENCE_COLLATERAL_PRICE.1,
            REFERENCE_COLLATERAL_PRICE.2,
            now,
        ),
    );
    let m0_l_price_pk = set_price(
        &mut svm,
        seeds.next_byte(),
        PriceFixture::valid(
            LOAN_FEED_M0,
            REFERENCE_LOAN_PRICE.0,
            REFERENCE_LOAN_PRICE.1,
            REFERENCE_LOAN_PRICE.2,
            now,
        ),
    );
    let m1_c_price_pk = set_price(
        &mut svm,
        seeds.next_byte(),
        PriceFixture::valid(
            COLLATERAL_FEED_M1,
            REFERENCE_COLLATERAL_PRICE.0,
            REFERENCE_COLLATERAL_PRICE.1,
            REFERENCE_COLLATERAL_PRICE.2,
            now,
        ),
    );
    let m1_l_price_pk = set_price(
        &mut svm,
        seeds.next_byte(),
        PriceFixture::valid(
            LOAN_FEED_M1,
            REFERENCE_LOAN_PRICE.0,
            REFERENCE_LOAN_PRICE.1,
            REFERENCE_LOAN_PRICE.2,
            now,
        ),
    );

    let mut markets = vec![
        MarketCtx {
            label: "m0_spl_spl",
            market: m0_market,
            fee_position: m0_fee_position,
            collateral_vault: m0_cvault,
            loan_vault: m0_lvault,
            collateral_mint: m0_collateral_mint,
            loan_mint: m0_loan_mint,
            collateral_token_program: spl_token_interface::ID,
            loan_token_program: spl_token_interface::ID,
            collateral_feed_id: COLLATERAL_FEED_M0,
            loan_feed_id: LOAN_FEED_M0,
            collateral_price_pubkey: m0_c_price_pk,
            loan_price_pubkey: m0_l_price_pk,
            collateral_price: REFERENCE_COLLATERAL_PRICE,
            loan_price: REFERENCE_LOAN_PRICE,
            positions: Vec::with_capacity(NUM_ACTORS),
            collateral_atas: Vec::with_capacity(NUM_ACTORS),
            loan_atas: Vec::with_capacity(NUM_ACTORS),
            ledger: Ledger::default(),
            is_token2022_fee_market: false,
        },
        MarketCtx {
            label: "m1_token2022_fee",
            market: m1_market,
            fee_position: m1_fee_position,
            collateral_vault: m1_cvault,
            loan_vault: m1_lvault,
            collateral_mint: m1_collateral_mint,
            loan_mint: m1_loan_mint,
            collateral_token_program: spl_token_2022_interface::ID,
            loan_token_program: spl_token_interface::ID,
            collateral_feed_id: COLLATERAL_FEED_M1,
            loan_feed_id: LOAN_FEED_M1,
            collateral_price_pubkey: m1_c_price_pk,
            loan_price_pubkey: m1_l_price_pk,
            collateral_price: REFERENCE_COLLATERAL_PRICE,
            loan_price: REFERENCE_LOAN_PRICE,
            positions: Vec::with_capacity(NUM_ACTORS),
            collateral_atas: Vec::with_capacity(NUM_ACTORS),
            loan_atas: Vec::with_capacity(NUM_ACTORS),
            ledger: Ledger::default(),
            is_token2022_fee_market: true,
        },
    ];

    for m in markets.iter_mut() {
        for actor in actors.iter() {
            let (_, position) = init_position(&mut svm, &admin, m.market, actor.pubkey());
            m.positions.push(position);

            let collateral_mint_extensions: &[spl_token_2022_interface::extension::ExtensionType] =
                if m.is_token2022_fee_market {
                    &[spl_token_2022_interface::extension::ExtensionType::TransferFeeConfig]
                } else {
                    &[]
                };
            let c_ata = create_token_account(
                &mut svm,
                &admin,
                seeds.next_byte(),
                m.collateral_mint,
                actor.pubkey(),
                m.collateral_token_program,
                collateral_mint_extensions,
            );
            mint_to(
                &mut svm,
                &admin,
                m.collateral_mint,
                c_ata,
                &admin,
                INITIAL_COLLATERAL_BALANCE,
                m.collateral_token_program,
            );
            m.collateral_atas.push(c_ata);

            let l_ata = create_token_account(
                &mut svm,
                &admin,
                seeds.next_byte(),
                m.loan_mint,
                actor.pubkey(),
                m.loan_token_program,
                &[],
            );
            mint_to(
                &mut svm,
                &admin,
                m.loan_mint,
                l_ata,
                &admin,
                INITIAL_LOAN_BALANCE,
                m.loan_token_program,
            );
            m.loan_atas.push(l_ata);
        }
    }

    World {
        svm,
        admin,
        actors,
        markets,
    }
}

impl World {
    /// Directly seeds a bad-debt-eligible position (`collateral_amount == 0`,
    /// `borrow_shares > 0`) via the same `seed_borrow_state` fixture-injection technique
    /// `tests/phase6_bad_debt.rs::setup_bad_debt_position` already uses -- TEST CODE ONLY, never
    /// reachable from a real instruction (`aegis_test_kit::state_injection`'s own module doc).
    ///
    /// Organic random liquidation only reaches EXACT-zero collateral rarely (it requires HF deep
    /// enough for a full, not partial, seizure), which makes `absorb_bad_debt`'s precondition a
    /// needle in the haystack for a pure random walk within any practical operation budget. This
    /// targeted seed is what makes the INV-SOLV-04 mutation-validation probe
    /// (`docs/security/mutation-report.md`) able to reach `absorb_bad_debt` at all within a
    /// bounded budget, exactly the kind of "improve ... state setup" the acceptance rule calls for
    /// (`docs/phases/phase-10-security.md` #29) rather than an unbounded random search.
    pub fn seed_bad_debt_position(&mut self, market_idx: usize, actor_idx: usize, bad_assets: u64) {
        let position = self.position_of(market_idx, actor_idx);
        let market = self.markets[market_idx].market;
        aegis_test_kit::seed_borrow_state(
            &mut self.svm,
            market,
            position,
            bad_assets,
            bad_assets as u128 * 1_000_000,
        );
    }

    pub fn now(&self) -> i64 {
        self.svm.get_sysvar::<solana_clock::Clock>().unix_timestamp
    }

    pub fn position_of(&self, market_idx: usize, actor_idx: usize) -> Pubkey {
        self.markets[market_idx].positions[actor_idx]
    }

    /// Every position PDA in `market_idx`, for `assert_all_global`'s `positions: &[Pubkey]`.
    pub fn all_positions(&self, market_idx: usize) -> Vec<Pubkey> {
        self.markets[market_idx].positions.clone()
    }

    pub fn fetch_market_state(&self, market_idx: usize) -> aegis::state::Market {
        fetch_market(&self.svm, &self.markets[market_idx].market)
    }

    pub fn fetch_position_state(
        &self,
        market_idx: usize,
        actor_idx: usize,
    ) -> aegis::state::Position {
        fetch_position(&self.svm, &self.position_of(market_idx, actor_idx))
    }
}
