//! Byte-exact Pyth `PriceUpdateV2` account construction (ADR-0008, `docs/oracle-design.md` §5).
//!
//! **TEST CODE ONLY — never a program dependency** (`architecture.md` §3: nothing in
//! `programs/aegis` imports this crate). This module constructs a real
//! `pyth_solana_receiver_sdk::price_update::PriceUpdateV2` value and serializes it with the real
//! SDK's own `AccountSerialize` impl (discriminator + Borsh, generated by the same `#[account]`
//! macro expansion the program's `oracle::pyth::PythPull` deserializes with via
//! `PriceUpdateV2::try_deserialize`) — never a hand-rolled byte-layout guess. If the fixture ever
//! drifted from the real account layout, `deserializes_via_real_sdk` below would fail loudly,
//! which is the point (ADR-0008 "Negative" consequences).
//!
//! No Hermes, no RPC, no Pyth program deployment: consuming a price update is an account read
//! (`oracle-design.md` §5), so `inject_price_update` only ever needs to set the account's raw
//! bytes and owner via `LiteSVM::set_account` — the same technique `state_injection.rs` already
//! established for `Market`/`Position` fixtures.

use anchor_lang::AccountSerialize;
use litesvm::LiteSVM;
use pyth_solana_receiver_sdk::price_update::{PriceFeedMessage, PriceUpdateV2, VerificationLevel};
use solana_account::Account as RawAccount;
use solana_pubkey::Pubkey;

/// Fixture account lamports. The exact figure is irrelevant to an account read; nonzero just
/// keeps the account "alive" the way a real posted price-update account would be.
const FIXTURE_LAMPORTS: u64 = 1_000_000_000;

/// Every knob a Phase 5 test needs to vary, in one place
/// (`docs/phases/phase-05-oracle.md` #29: "feed ID, price, confidence, exponent, publish time,
/// verification level, owner").
#[derive(Clone, Copy, Debug)]
pub struct PriceFixture {
    pub feed_id: [u8; 32],
    pub price: i64,
    pub conf: u64,
    pub exponent: i32,
    pub publish_time: i64,
    pub prev_publish_time: i64,
    pub ema_price: i64,
    pub ema_conf: u64,
    pub verification_level: VerificationLevel,
    pub posted_slot: u64,
    /// Overridable so `A-ORACLE-06` can construct an otherwise well-formed account owned by the
    /// wrong program.
    pub owner: Pubkey,
    pub write_authority: Pubkey,
}

impl PriceFixture {
    /// A conservatively "valid" starting point: `Full` verification, published at `now`, tight
    /// (zero) confidence, owned by the real Pyth receiver program. Callers override only the
    /// field(s) their test cares about via struct-update syntax.
    pub fn valid(feed_id: [u8; 32], price: i64, conf: u64, exponent: i32, now: i64) -> Self {
        Self {
            feed_id,
            price,
            conf,
            exponent,
            publish_time: now,
            prev_publish_time: now.saturating_sub(1),
            ema_price: price,
            ema_conf: conf,
            verification_level: VerificationLevel::Full,
            posted_slot: 0,
            owner: pyth_solana_receiver_sdk::ID,
            write_authority: Pubkey::new_unique(),
        }
    }

    /// Builds the real `PriceUpdateV2` value this fixture describes.
    pub fn to_price_update(self) -> PriceUpdateV2 {
        PriceUpdateV2 {
            write_authority: self.write_authority,
            verification_level: self.verification_level,
            price_message: PriceFeedMessage {
                feed_id: self.feed_id,
                price: self.price,
                conf: self.conf,
                exponent: self.exponent,
                publish_time: self.publish_time,
                prev_publish_time: self.prev_publish_time,
                ema_price: self.ema_price,
                ema_conf: self.ema_conf,
            },
            posted_slot: self.posted_slot,
        }
    }

    /// Serializes the fixture using the REAL SDK's own `AccountSerialize` impl (8-byte
    /// discriminator + Borsh) — the exact bytes `oracle::pyth::PythPull::read_price` deserializes
    /// with `PriceUpdateV2::try_deserialize`.
    pub fn serialize(self) -> Vec<u8> {
        let price_update = self.to_price_update();
        let mut data = Vec::new();
        price_update
            .try_serialize(&mut data)
            .expect("serialize a real PriceUpdateV2 via the SDK's own AccountSerialize impl");
        data
    }
}

/// Injects `fixture` into `svm` at `pubkey`, owned by `fixture.owner` (normally the real Pyth
/// receiver program ID; `A-ORACLE-06` overrides it to a wrong-owner program to prove the explicit
/// O-1 check fires).
pub fn inject_price_update(svm: &mut LiteSVM, pubkey: Pubkey, fixture: PriceFixture) {
    let owner = fixture.owner;
    let data = fixture.serialize();
    svm.set_account(
        pubkey,
        RawAccount {
            lamports: FIXTURE_LAMPORTS,
            data,
            owner,
            executable: false,
            rent_epoch: 0,
        },
    )
    .expect("failed to inject Pyth price-update fixture");
}

/// Convenience: deterministically derives a fresh price-update pubkey from a one-byte seed and
/// injects `fixture` there, returning the pubkey. Keeps call sites in tests/demo one-liners.
pub fn set_price(svm: &mut LiteSVM, seed: u8, fixture: PriceFixture) -> Pubkey {
    let pubkey = Pubkey::new_from_array([seed; 32]);
    inject_price_update(svm, pubkey, fixture);
    pubkey
}

#[cfg(test)]
mod tests {
    use super::*;
    use anchor_lang::AccountDeserialize;

    // Evidence required by docs/phases/phase-05-oracle.md #29 and ADR-0008: construct fixture
    // bytes, deserialize them with the REAL SDK's own account-loading API (not this crate's own
    // struct), and assert every field survives the round trip exactly.
    #[test]
    fn deserializes_via_real_sdk() {
        let feed_id = [7u8; 32];
        let fixture = PriceFixture::valid(feed_id, 15_000_000_000, 30_000_000, -8, 1_700_000_000);
        let bytes = fixture.serialize();

        // The real SDK's own deserializer -- the identical call `oracle::pyth::PythPull` makes.
        let mut slice: &[u8] = &bytes;
        let decoded = PriceUpdateV2::try_deserialize(&mut slice)
            .expect("the real pyth-solana-receiver-sdk must deserialize our fixture bytes");

        assert_eq!(decoded.price_message.feed_id, feed_id);
        assert_eq!(decoded.price_message.price, 15_000_000_000);
        assert_eq!(decoded.price_message.conf, 30_000_000);
        assert_eq!(decoded.price_message.exponent, -8);
        assert_eq!(decoded.price_message.publish_time, 1_700_000_000);
        assert_eq!(decoded.verification_level, VerificationLevel::Full);
        assert_eq!(decoded.write_authority, fixture.write_authority);
    }

    // Byte-exactness also holds for the `Partial` verification-level variant (A-ORACLE-08 uses
    // this shape).
    #[test]
    fn deserializes_partial_verification_level() {
        let mut fixture = PriceFixture::valid([1u8; 32], 100, 0, 0, 1_000);
        fixture.verification_level = VerificationLevel::Partial { num_signatures: 5 };
        let bytes = fixture.serialize();

        let mut slice: &[u8] = &bytes;
        let decoded = PriceUpdateV2::try_deserialize(&mut slice).unwrap();
        assert_eq!(
            decoded.verification_level,
            VerificationLevel::Partial { num_signatures: 5 }
        );
    }

    // Deterministic: the identical fixture serializes to the identical bytes every time, and two
    // different LiteSVM instances end up with byte-identical injected accounts -- no timestamp,
    // RNG, or non-determinism anywhere in the fixture path.
    #[test]
    fn is_fully_deterministic() {
        let fixture = PriceFixture {
            write_authority: Pubkey::new_from_array([9u8; 32]),
            ..PriceFixture::valid([2u8; 32], 500, 1, -2, 42)
        };
        assert_eq!(fixture.serialize(), fixture.serialize());
    }
}
