// I-SDK-03: proves TypeScript PDA derivation matches the real on-chain/Rust derivation exactly,
// for representative and boundary cases (multiple pubkeys, multiple config IDs, user Position, fee
// Position, vaults, and specifically config_id values chosen to catch an endian mistake in the u16
// seed encoding). The "ground truth" comes from `tests/vectors/pdas.json`, generated by calling the
// SAME `Pubkey::find_program_address`-based helpers every Rust test in this repository uses
// (`crates/aegis-test-kit/src/market.rs`) -- never a hand-computed expected address.

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { address, type Address } from '@solana/kit';
import { describe, expect, it } from 'vitest';
import {
  collateralVaultPda,
  loanVaultPda,
  marketPda,
  positionPda,
  protocolPda,
} from '../src/pda.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const VECTORS_DIR = path.resolve(__dirname, '../../../tests/vectors');

const v = JSON.parse(readFileSync(path.join(VECTORS_DIR, 'pdas.json'), 'utf8'));
const programId: Address = address(v.programId);

describe('I-SDK-03 -- PDA derivation parity', () => {
  it('protocol PDA matches exactly', async () => {
    const protocolCase = v.cases.find((c: any) => c.name === 'protocol');
    const derived = await protocolPda(programId);
    expect(derived).toBe(protocolCase.address);
  });

  for (const c of v.cases.filter((c: any) => c.name.startsWith('market_'))) {
    it(`market/vault PDAs match exactly: ${c.name}`, async () => {
      const collateralMint = address(c.inputs.collateralMint);
      const loanMint = address(c.inputs.loanMint);
      const market = await marketPda(programId, collateralMint, loanMint, c.inputs.configId);
      expect(market).toBe(c.market.address);

      const collateralVault = await collateralVaultPda(programId, market);
      expect(collateralVault).toBe(c.collateralVault.address);

      const loanVault = await loanVaultPda(programId, market);
      expect(loanVault).toBe(c.loanVault.address);
    });
  }

  for (const c of v.cases.filter((c: any) => c.name.startsWith('position_'))) {
    it(`position PDA matches exactly: ${c.name}`, async () => {
      const market = address(c.inputs.market);
      const owner = address(c.inputs.owner);
      const position = await positionPda(programId, market, owner);
      expect(position).toBe(c.position.address);
    });
  }

  it('config_id=1 and config_id=256 derive to DIFFERENT addresses (endian sanity check)', () => {
    const c1 = v.cases.find((c: any) => c.name === 'market_a_b_config_1');
    const c256 = v.cases.find((c: any) => c.name === 'market_a_b_config_256');
    expect(c1.market.address).not.toBe(c256.market.address);
  });
});
