// Reads a Pyth `PriceUpdateV2` account (as posted/injected locally, ADR-0008) for display
// purposes only -- this mirrors the real crate's own field layout
// (`pyth_solana_receiver_sdk::price_update::PriceUpdateV2`, verified directly against
// `crates/aegis-test-kit/src/pyth_fixture.rs`'s construction of the same real SDK type), never a
// second on-chain trust decision: the actual security-relevant validation (O-1..O-11) happens only
// on-chain, inside `borrow`/`withdraw_collateral`/`liquidate` themselves. This is advisory,
// UI-only, exactly like `bots/liquidator/src/health.ts`'s off-chain estimate.
//
// Layout after the 8-byte Anchor account discriminator (borsh, field order from the real struct):
//   write_authority: Pubkey (32 bytes, skipped)
//   verification_level: enum tag (u8) -- 0 = Partial{num_signatures: u8} (9 bytes total), 1 = Full
//   price_message: { feed_id: [u8;32], price: i64, conf: u64, exponent: i32, publish_time: i64,
//                    prev_publish_time: i64 (skipped), ema_price: i64 (skipped),
//                    ema_conf: u64 (skipped) }
//   posted_slot: u64 (skipped)

export interface OnChainPriceUpdate {
  feedId: Uint8Array;
  price: bigint;
  conf: bigint;
  expo: number;
  publishTime: bigint;
}

// The real Anchor account discriminator for `PriceUpdateV2` (`sha256("account:PriceUpdateV2")[0..8]`),
// extracted directly from a real fixture byte-dump produced by the actual
// `pyth_solana_receiver_sdk`/`aegis_test_kit::PriceFixture` serialization
// (`sdk/ts/fixtures/prices.json`, generated by `crates/aegis-test-kit/examples/
// phase8_price_fixture_dump.rs`) -- never typed from memory. Verified once, ground truth from a
// real serialized account, not re-derived here.
const PRICE_UPDATE_V2_DISCRIMINATOR = Uint8Array.from([34, 241, 35, 99, 157, 126, 244, 205]);

/** Encodes a `PriceUpdateV2` account's bytes for local injection via Surfpool's
 *  `surfnet_setAccount` cheat-code (ADR-0008's fixture-injection pattern, client-side variant of
 *  what `crates/aegis-test-kit/src/pyth_fixture.rs` does for every Rust test/demo). Always
 *  `VerificationLevel::Full` (tag `1`, no extra bytes) -- the only level any Aegis check accepts. */
export function encodePriceUpdateV2(
  feedId: Uint8Array,
  price: bigint,
  conf: bigint,
  expo: number,
  publishTimeSecs: bigint,
): Uint8Array {
  const buf = new Uint8Array(133);
  const view = new DataView(buf.buffer);
  buf.set(PRICE_UPDATE_V2_DISCRIMINATOR, 0);
  // write_authority (32 bytes) left zero -- never read by `oracle::pyth::PythPull::read_price`.
  view.setUint8(40, 1); // VerificationLevel::Full
  buf.set(feedId, 41);
  view.setBigInt64(73, price, true);
  view.setBigUint64(81, conf, true);
  view.setInt32(89, expo, true);
  view.setBigInt64(93, publishTimeSecs, true); // publish_time
  view.setBigInt64(101, publishTimeSecs, true); // prev_publish_time
  view.setBigInt64(109, price, true); // ema_price
  view.setBigUint64(117, conf, true); // ema_conf
  view.setBigUint64(125, 1n, true); // posted_slot
  return buf;
}

export function decodePriceUpdateV2(data: Uint8Array): OnChainPriceUpdate {
  const view = new DataView(data.buffer, data.byteOffset, data.byteLength);
  let offset = 8 + 32; // discriminator + write_authority

  const verificationTag = view.getUint8(offset);
  offset += 1;
  if (verificationTag === 0) offset += 1; // Partial{num_signatures: u8}

  const feedId = data.slice(offset, offset + 32);
  offset += 32;

  const price = view.getBigInt64(offset, true);
  offset += 8;
  const conf = view.getBigUint64(offset, true);
  offset += 8;
  const expo = view.getInt32(offset, true);
  offset += 4;
  const publishTime = view.getBigInt64(offset, true);

  return { feedId, price, conf, expo, publishTime };
}
